name: Quality Check
on:
  push:
    branches:
      - "*" # matches every branch
      - "*/*" # matches every branch containing a single '/'
      - "!master" # excludes master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
      
      - name: Install dependencies
        run: npm install
      
      - run: npm test
        env:
          CI: true
      
      - run: npm build
