name: Quality Check
on:
  push:
    branches:
      - "*" # matches every branch
      - "*/*" # matches every branch containing a single '/'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test
        env:
          CI: true
      
      - name: Run build
        run: npm build
